version: '3'
services:
    web:
      image: fauria/lamp
      volumes:
        - "./app:/var/www/html"
        - "./logs:/var/log/apache2"
      ports:
        - "${WEB_PORT}:80"
      environment:
        - LOG_STDOUT=true 
      depends_on:
        - mysql
    composer:
      image: "composer"
      volumes:
          - "./app:/app"
      command: install
    mysql:
      image: mysql:${MYSQL_VERSION}
      container_name: ${MYSQL_HOST}
      restart: always
      env_file:
          - ".env"
      environment:
          - MYSQL_DATABASE=${MYSQL_DATABASE}
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      ports:
          - "8989:3306"
      volumes:
          - "./data/db/mysql:/var/lib/mysql"